name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: gold-gearbox-390112          # Replace with your actual GCP project ID
  REGION: us-central1                      # Change to your desired GCP region (e.g., asia-south1 for Mumbai)
  REPO: my-docker-repositoy	               # Name of your Artifact Registry Docker repo
  SERVICE: testcloudrunservice           # Name of your Cloud Run service
  SPRING_PROFILE: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE:$GITHUB_SHA \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated \
            --set-env-vars SPRING_PROFILES_ACTIVE=${{ env.SPRING_PROFILE }},DB_URL=${{ secrets.DB_URL }},DB_USER=${{ secrets.DB_USER }},DB_PASS=${{ secrets.DB_PASS }}

